version: '3'
services:
    nodejs:
        image: xpe_tdd_api
        restart: always
        build: .
        ports:
            - 3000
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        volumes:
            - $HOME/volumes/xpe-postgres:/var/lib/postgresql/data
        ports:
            - 5432
        environment:
            - POSTGRES_PASSWORD=mysecretpassword
